### ISSUE TITLE
System.Argument Exception when using CSP middleware with UseStatusCodePagesWithReExecute middleware

### ISSUE THREAD

**Issue by mattparry43** [juunas11/aspnetcore-security-headers#19]
Hi! We're using your package in a couple of our ASP.NET Core 2.0 apps, and came across errors like this in our logs:

```
System.ArgumentException: An item with the same key has already been added. Key: Content-Security-Policy
   at System.ThrowHelper.ThrowAddingDuplicateWithKeyArgumentException(Object key)
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.FrameResponseHeaders.AddValueFast(String key, StringValues value)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.FrameHeaders.System.Collections.Generic.IDictionary<System.String,Microsoft.Extensions.Primitives.StringValues>.Add(String key, StringValues value)
   at Joonasw.AspNetCore.SecurityHeaders.Csp.CspMiddleware.<Invoke>d__5.MoveNext()
```

We are also using the `UseStatusCodePagesWithReExecute` middleware in our pipeline to handle Status Codes. After some debugging, we found that:

- If we add the CSP middleware _after_ `UseStatusCodePagesWithReExecute`, then the Exception is thrown if the `UseStatusCodePagesWithReExecute` is invoked (i.e. when a Controller Action uses `StatusCode`), and is not thrown otherwise.
- If we add the CSP middleware _before_ `UseStatusCodePagesWithReExecute` then no Exception is thrown.

Since the `UseStatusCodePagesWithReExecute` middleware causes subsequent middleware to be invoked again, we deduced that the CSP middleware must be getting invoked twice, and is trying to add the `Content-Security-Policy` header again, causing the exception to be thrown. We found that in your package, the `CspMiddleware` adds to the Response Headers collection without first checking if the item already exists.

What would be your recommendation - should we add add the CSP middleware to our pipeline before `UseStatusCodePagesWithReExecute`, or could you add a check in the middleware to only add the header if it is not already set?

**Comment by juunas11** [comment]
Thanks for the report! I think it's best if I make a patch to check for the header first :)

**Comment by mattparry43** [comment]
Amazing, thank you!

**Comment by juunas11** [comment]
Version 2.5.1 will be available on nuget soon :relaxed:
